### ISSUE TITLE
Preparação do computador

### ISSUE THREAD

**Issue by rsoutelino** [rsoutelino/uerj-pythoncourse-20150629#1]
Este espaço é para discutir coisas relacionadas a instalação de pacotes necessário para o curso.

**Comment by phellipecouto** [comment]
testing...

**Comment by rsoutelino** [comment]
Acessem o link abaixo para informações gerais sobre o curso e preparação dos computadores:

http://rsoutelino.github.io/ca-faoc-pythoncourse/

E o link abaixo, que faz parte deste repositório, para navegar nos assuntos e/ou criar novos assuntos (issues). 

https://github.com/rsoutelino/uerj-pythoncourse-20150629/issues
