### ISSUE TITLE
Preparação para as aulas

### ISSUE THREAD

**Issue by rsoutelino** [rsoutelino/uerj-pythoncourse-20150629#2]
Comunicados e dúvidas sobre preparação para as aulas durante a semana do curso.

**Comment by phellipecouto** [comment]
testing..

**Comment by rsoutelino** [comment]
Boa tarde pessoal, hoje o assunto da aula será séries temporais - leitura, análise, plotagem. Usaremos uma poderosa biblioteca em python chamada **pandas**. Para apresentar o pandas a vocês, usarei as notas de aula do Nicholas, no link abaixo. Posteriormente, iremos manipular séries temporais que os alunos colocaram em nosso repositório. 

http://nbviewer.ipython.org/github/nicolasfauchereau/metocean/blob/master/notebooks/pandas.ipynb
