### ISSUE TITLE
Lista de alunos

### ISSUE THREAD

**Issue by rsoutelino** [rsoutelino/uerj-pythoncourse-20150629#3]
Para controle dos que criaram a conta no github. 

Acessem o link abaixo para informações gerais sobre o curso e preparação dos computadores:

http://rsoutelino.github.io/ca-faoc-pythoncourse/

E o link abaixo, que faz parte deste repositório, para navegar nos assuntos e/ou criar novos assuntos (issues). 

https://github.com/rsoutelino/uerj-pythoncourse-20150629/issues

**Comment by phellipecouto** [comment]
testing...

**Comment by eduardocrichard** [comment]
Usuário

**Comment by juafernandes** [comment]
juafernandes

**Comment by douglasnehme** [comment]
douglasnehme

**Comment by rafaellapagesse** [comment]
rafaellapagesse

**Comment by victor-ocn** [comment]
victor-ocn

**Comment by diogolannes** [comment]
diogolannes

**Comment by luizagbrito** [comment]
luizagbrito

**Comment by vieirarc** [comment]
vieirarc

**Comment by fellipetavares** [comment]
fellipetavares

**Comment by lusmachado** [comment]
lusmachado

**Comment by naragarcia23** [comment]
naragarcia23

**Comment by DanielCervai** [comment]
DanielCervai

**Comment by camilacotrim** [comment]
camilacotrim

**Comment by laisnaval** [comment]
laisnaval

**Comment by giuliamolina** [comment]
giuliamolina

**Comment by FlavioACGomes** [comment]
![captura de tela 2015-02-23 as 13 49 53](https://cloud.githubusercontent.com/assets/13071767/8389688/176c8304-1c4c-11e5-863e-676a9f53a086.png)
FlavioACGomes

**Comment by FlavioACGomes** [comment]
FlavioACGomes

**Comment by andrekorol** [comment]
andrekorol

**Comment by souzalayss** [comment]
souzalayss

**Comment by lupeiter** [comment]
lupeiter

**Comment by camilareveles** [comment]
camilareveles

**Comment by jskaiser** [comment]
jskaiser

**Comment by pzau** [comment]
pnszau

**Comment by daniellerey** [comment]
daniellerey

**Comment by Gam2011** [comment]
Gam2011

**Comment by alinesantana** [comment]
alinesantana

**Comment by dyyhqueiroz** [comment]
dyyhqueiroz

**Comment by FelipeLage** [comment]
FelipeLage

**Comment by thiagoieapm** [comment]
thiagoieapm
ThiagoMatos

**Comment by jfelipemaia** [comment]
jfelipemaia

**Comment by fernandamr** [comment]
fernandamr
