### ISSUE TITLE
Dúvidas de cunho geral

### ISSUE THREAD

**Issue by rsoutelino** [rsoutelino/uerj-pythoncourse-20150629#4]
Espaço para dúvidas que não se enquadram nos assuntos específicos.

**Comment by juafernandes** [comment]
Olá professor,

você poderia indicar fóruns? Obrigada.

**Comment by rsoutelino** [comment]
Para programação em geral, um dos melhores é o http://stackoverflow.com/

**Comment by rsoutelino** [comment]
Bom site para dicas de producao de figuras com qualidade de publicacao

https://github.com/crocha700/matplotlib_for_papers
